default_install_hook_types: [pre-commit, commit-msg]
default_stages: [pre-commit]
exclude: |
  (?x)(
      ^assets/|
      ^docs/.*.html|
      ^_extensions/|
      ^nextflow_schema.json|
      ^.*.svg |
      ^.github/CONTRIBUTING.md|
      ^resources/HOCOMOCO|
      ^resources/blacklistbed|
      ^resources/cCREs|
      ^resources/spikein|
      ^resources/tss_bed
   )
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-added-large-files
        args: ["--maxkb=10240"]
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-json
  # spell check
  - repo: https://github.com/codespell-project/codespell
    rev: v2.4.2
    hooks:
      - id: codespell
        args: ["-I", ".github/WORDLIST.txt"]
  # Python formatting
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.12
    hooks:
      - id: ruff-check
        args: [--fix]
      - id: ruff-format
  # R formatting
  - repo: https://github.com/posit-dev/air-pre-commit
    rev: 0.9.0
    hooks:
      - id: air-format
  # general linting
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "v4.0.0-alpha.8"
    hooks:
      - id: prettier
        additional_dependencies:
          - prettier@3.4.0
  # enforce commit format
  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v4.4.0
    hooks:
      - id: conventional-pre-commit
        stages: [commit-msg]
        args: []
  - repo: https://github.com/citation-file-format/cffconvert
    rev: 054bda51dbe278b3e86f27c890e3f3ac877d616c
    hooks:
      - id: validate-cff
