---
title: "Spike-in Control QC Assessment"
author: "Samantha Sevilla"
date: "`r Sys.Date()`"
output:
  html_document:
params:
  carlisle_functions: "/data/CCBR_Pipeliner/Pipelines/CARLISLE/latest/workflow/scripts/_carlisle_functions.R"
  Rlib_dir: "/data/CCBR_Pipeliner/db/PipeDB/Rlibrary_4.3_carlisle/"
  Rpkg_config: "/data/CCBR_Pipeliner/Pipelines/CARLISLE/latest/conf/Rpack.config"
  carlisle_functions: "~/../../Volumes/Pipelines/CARLISLE_dev/workflow/scripts/_carlisle_functions.R"
  bam_list: "~/../../Volumes/data/carlisle/v2.0/results/bam/raw/53_H3K4me3_1.bam.idxstatsxxx~/../../Volumes/data/carlisle/v2.0/results/bam/raw/53_H3K4me3_2.bam.idxstatsxxx~/../../Volumes/data/carlisle/v2.0/results/bam/raw/HN6_H3K4me3_1.bam.idxstatsxxx~/../../Volumes/data/carlisle/v2.0/results/bam/raw/HN6_H3K4me3_2.bam.idxstatsxxx~/../../Volumes/data/carlisle/v2.0/results/bam/raw/53_H4K20m3_1.bam.idxstatsxxx~/../../Volumes/data/carlisle/v2.0/results/bam/raw/53_H4K20m3_2.bam.idxstatsxxx~/../../Volumes/data/carlisle/v2.0/results/bam/raw/HN6_H4K20me3_1.bam.idxstatsxxx~/../../Volumes/data/carlisle/v2.0/results/bam/raw/HN6_H4K20me3_2.bam.idxstatsxxx~/../../Volumes/data/carlisle/v2.0/results/bam/raw/HN6_IgG_rabbit_negative_control_1.bam.idxstats"
  spikein_control: "NC_000913.3"
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

# source needed functions
carlisle_functions=params$carlisle_functions

# set library dir, load this and remove any other dirs to avoid confusion
# between personally created pkgs and the pipeline package
## saving old path "/Library/Frameworks/R.framework/Versions/4.2-arm64/Resources/library"
Rlib_dir=params$Rlib_dir
Rpkg_config=params$Rpkg_config
print(paste0("Using the lib.loc location: ",Rlib_dir))
assign(".lib.loc", Rlib_dir, envir = environment(.libPaths))
.libPaths()

# read in package info
pkg_df=read.csv(Rpkg_config)
pkg_df=subset(pkg_df,spike_in=="Y")
pkg_df

# for each package check installation, if present then load library
carlisle_handle_packages(pkg_df)
```


```{r params, include=FALSE, echo=FALSE}
# set params
bam_list=params$bam_list
spikein_control=params$spikein_control
debug="N"

if (debug=="Y"){
  spikein_control="NC_000913.3"
  bam_list=""
}

# set up bam list
bam_list=as.list(strsplit(bam_list, 'xxx'))[[1]]
```


```{r df, echo=FALSE}
# input list of all bams
# /data/sevillas2/carlisle/v2.0/results/bam/HN6_H4K20me3_2.dedup.bam.idxstats

# create df
proj_df=data.frame()
for (bam in bam_list){
  total_str_length=length(strsplit(bam,"/")[[1]])
  
  # example: # /data/sevillas2/carlisle/v2.0/results/bam/HN6_H4K20me3_2.dedup.bam.idxstats
  proj_df[nrow(proj_df)+1,"bam"]=bam
  
  # example: HN6_H4K20me3_2.dedup.bam.idxstats
  ext=strsplit(bam,"/")[[1]][total_str_length]
  
  # example: HN6_H4K20me3_2
  proj_df[nrow(proj_df),"repid"]=strsplit(ext,"[.]")[[1]][1]
  
  # example: HN6_H4K20me3
  proj_df[nrow(proj_df),"sampleid"]=gsub("_[1,2,3]","",proj_df[nrow(proj_df),"repid"])
}

DT::datatable(proj_df)
```

```{r spikeplot, echo=FALSE}
spike_df=GENERATE_SPIKEIN_PLOT(input_df=proj_df,
                      spike_type=spikein_control)
DT::datatable(spike_df)
```

