#!/usr/bin/env bash
# input:
## intake snakemake log
## full path to jobby.py script

# prep the logs by pulling IDs
snakemakelog=$1
jobids=$(grep --color=never "^Submitted .* with external jobid" $snakemakelog | awk '{print $NF}'  | sed "s/['.]//g" | sort | uniq | tr "\\n" " ")
jobidswc=$(echo $jobids | wc -c)

# run jobby script
module load python
if [ "$jobidswc" != "1" ];then python $2 $jobids; fi
