#!/usr/bin/env bash
# if running on Biowulf
# create a zip of essential files like dryrun and tree
# use spook to push the file to secret location on /scratch
#
# This scripts is created using _zip_tar_copy script from permfix as template
#

set -o pipefail
PIPELINE_OUTDIR=$1

SCONTROL=$(type -P scontrol)
if [[ "$SCONTROL" == "" ]];then
	echo "scontrol not in PATH!"
	exit
fi

nbiowulf=$(scontrol show config | grep -i -c biowulf)
if [[ "$nbiowulf" > 0 ]];then ISBIOWULF=true; else ISBIOWULF=false;fi
nfrce=$(scontrol show config | grep -i -c fsitgl)
if [[ "$nfrce" > 0 ]];then ISFRCE=true; else ISFRCE=false;fi

if [[ $ISBIOWULF == true || $ISFRCE == true ]];then
    if [[ $ISBIOWULF == true ]];then
        SPOOK=$(type -P spook)
        if [[ "$SPOOK" == "" ]];then
            echo "spook is not in PATH."
            echo "... trying to add it."
            # setup SPACESAVERS2DIR PERMFIXDIR PATHs etc.
            . "/data/CCBR_Pipeliner/cronjobs/scripts/setup"
            SPOOK=$(type -P spook)
            if [[ "$SPOOK" == "" ]];then
                echo "spook is still not in PATH!"
                exit
	    fi
        fi
        echo "spook is now in PATH:$SPOOK"
        SPOOK_COPY2DIR="/scratch/carlisle"
    fi
    if [[ $ISFRCE == true ]];then
        SPOOK_COPY2DIR="/mnt/projects/CCBR-Pipelines/pipelines/userdata/carlisle"
    fi

    DT=$(date +%y%m%d%H%M%S)
    archivefile="${HOME}/${USER}.${DT}.tar"
    treefile="${HOME}/${USER}.${DT}.tree"

    dryrunlogfile=""
    if [[ -d "$PIPELINE_OUTDIR" ]];then
        dryrunlogfile=$(ls -rt ${PIPELINE_OUTDIR}/dryrun*log 2>/dev/null |tail -n1 || echo "")
        cmd="tar cvf ${archivefile}"
        if [[ "$dryrunlogfile" != "" ]];then
            cmd="$cmd $dryrunlogfile"
        fi
        # gather some info
        echo "PIPELINE_OUTDIR:$PIPELINE_OUTDIR" > $treefile
        echo "USER:$USER" >> $treefile
        #GROUPS=$(groups 2>/dev/null)
        echo "GROUPS:" $(groups) >> $treefile
        CARLISLE=$(which CARLISLE)
        echo "CARLISLE:$CARLISLE" >> $treefile
        echo "DATE:$DT" >> $treefile
        tree $PIPELINE_OUTDIR >> $treefile
        cmd="$cmd $treefile"

        if [[ -d "${PIPELINE_OUTDIR}/logfiles" ]];then
            logdir="${PIPELINE_OUTDIR}/logfiles"
            for thisfile in "snakemake.log" "snakemake.log.jobby" "master.log" "runtime_statistics.json";do
                absthisfile="${logdir}/${thisfile}"
                if [[ -f "$absthisfile" ]];then
                    cmd="$cmd $absthisfile"
                fi
            done
        fi

        echo $cmd
        $cmd

        # copy over the archive to secrete location and delete it
        if [ -f "${archivefile}" ];then
            gzip -f $archivefile
            if [[ $ISBIOWULF == true ]]; then
                cmd="$SPOOK -f ${archivefile}.gz -d $SPOOK_COPY2DIR"
                echo $cmd
                $cmd
            fi
            if [[ $ISFRCE == true ]];then
                cmd="cp -rv ${archivefile}.gz $SPOOK_COPY2DIR"
                echo $cmd
                $cmd
            fi
            rm -f ${archivefile}.gz $treefile
        fi
    fi

else # not biowulf or frce ... so exit
    exit 0
fi