name: lintr

on:
  push:
    branches:
      - master
      - dev
jobs:
  Lintr:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: docker://snakemake/snakemake:v7.19.1
    - name: Lint Workflow
      continue-on-error: true
      run: |
        mkdir /opt2/output_carlisle
        cp workflow/scripts/* /opt2/output_carlisle
        docker run -v $PWD:/opt2 snakemake/snakemake:v7.19.1 snakemake --lint -s /opt2/workflow/Snakefile -d /opt2/output_carlisle --configfile /opt2/.test/config_lint.yaml || \
        echo 'There may have been a few warnings or errors. Please read through the log to determine if its harmless.'